"""All physical inputs; defaults are illustrative, not crane specifications."""
from dataclasses import dataclass, field, fields
import math


def parameter(default, unit, meaning, status="placeholder", minimum=0.0, maximum=1e6):
    return field(default=default, metadata=dict(unit=unit, meaning=meaning,
                 status=status, minimum=minimum, maximum=maximum))


@dataclass(frozen=True)
class Parameters:
    mass: float = parameter(100.0, "kg", "Suspended load mass", minimum=0.001)
    radius: float = parameter(0.1, "m/rad", "Load travel per motor-shaft radian; drum radius / gear ratio", minimum=0.0001, maximum=100)
    inertia: float = parameter(1.0, "kg m²", "Rotational inertia at shaft, excluding suspended mass")
    damping: float = parameter(0.2, "N m s/rad", "Viscous shaft friction coefficient")
    brake_torque: float = parameter(150.0, "N m", "Static and sliding brake torque capacity at shaft")
    brake_response: float = parameter(0.3, "s", "Brake application/release time constant (0 = instantaneous)", maximum=60)
    brake_release_delay: float = parameter(0.0, "s", "Delay from RELEASE command to physical release motion", "estimated", maximum=10)
    brake_application_delay: float = parameter(0.0, "s", "Delay from APPLY command to physical application motion", "estimated", maximum=10)
    crane_height: float = parameter(10.0, "m", "Initial clearance below load; maximum downward travel", minimum=0.01, maximum=10000)
    gravity: float = parameter(9.81, "m/s²", "Constant gravitational acceleration", "estimated", maximum=100)
    supply_frequency: float = parameter(5.0, "Hz", "Ideal rotating-field frequency, lowering direction", minimum=0.1, maximum=100)
    pole_pairs: float = parameter(2, "pairs", "Motor pole pairs (integer; 2 pairs = 4 poles)", minimum=1, maximum=20)
    peak_motor_torque: float = parameter(120.0, "N m", "Peak magnitude of the assumed torque-slip curve", maximum=10000)
    peak_slip: float = parameter(0.2, "1", "Slip magnitude at peak motor/generator torque", minimum=0.01, maximum=1)
    volts_per_hz: float = parameter(8.0, "V/Hz", "Commanded line-line RMS voltage / frequency", maximum=100)
    reference_volts_per_hz: float = parameter(8.0, "V/Hz", "V/f at which the peak torque parameter is defined", minimum=0.1, maximum=100)
    magnetizing_inductance: float = parameter(0.2, "H/phase", "Linear star-equivalent magnetizing inductance", minimum=0.001, maximum=100)
    capacitor_capacitance: float = parameter(1000.0, "µF/branch", "Each of three delta-connected AC capacitors", maximum=100000)
    stator_resistance: float = parameter(0.5, "ohm/phase", "Dynamic model: stator winding resistance", minimum=0.01, maximum=100)
    rotor_resistance: float = parameter(0.4, "ohm/phase", "Dynamic model: rotor resistance referred to stator", minimum=0.01, maximum=100)
    stator_leakage: float = parameter(0.01, "H/phase", "Dynamic model: stator leakage inductance", minimum=0.001, maximum=1)
    rotor_leakage: float = parameter(0.01, "H/phase", "Dynamic model: referred rotor leakage inductance", minimum=0.001, maximum=1)
    saturation_flux: float = parameter(1.0, "Wb turn", "Flux where nonlinear magnetizing current is twice its linear value", minimum=0.01, maximum=10)
    initial_flux: float = parameter(0.005, "Wb turn", "Initial residual-flux seed; initial condition, not a hysteresis model", maximum=1)
    precharge_voltage: float = parameter(80.0, "V LL equiv.", "Capacitor-bank target supplied by the 24 V precharge converter", maximum=1000)
    initial_shaft_rpm: float = parameter(0.0, "RPM", "Dynamic model: shaft speed at Reset", maximum=3000)
    ac_load_resistance: float = parameter(100.0, "ohm/phase", "Balanced star AC test load; larger values mean lighter load", minimum=1, maximum=100000)
    excitation_response: float = parameter(0.05, "s", "Exciter voltage / flux feedback response time", minimum=0.001, maximum=1)
    motor_rated_voltage: float = parameter(400.0, "V LL RMS", "Nameplate voltage; reference for the overview voltage bar", "estimated", minimum=1, maximum=1000)
    dc_capacitance: float = parameter(470.0, "µF", "DC-link smoothing capacitor", "estimated", minimum=10, maximum=100000)
    dc_initial_voltage: float = parameter(0.0, "V", "Initial DC-link voltage at reset", "estimated", maximum=1500)
    rectifier_resistance: float = parameter(10.0, "ohm", "Effective averaged bridge/source resistance; limits charging current", "estimated", minimum=1, maximum=1000)
    dc_brake_resistance: float = parameter(390.0, "ohm", "DC equivalent brake resistance; smaller draws more current at a given voltage", "estimated", minimum=10, maximum=100000)
    chopper_reference_frequency: float = parameter(20.0, "Hz", "Frequency at which the scheduled chopper target equals its reference voltage", "estimated", minimum=0.1, maximum=100)
    chopper_reference_voltage: float = parameter(400.0, "V DC", "Normal DC-link control target at the chopper reference frequency", "estimated", minimum=10, maximum=1500)
    chopper_min_operating_voltage: float = parameter(80.0, "V DC", "Minimum scheduled normal chopper target", "estimated", minimum=0, maximum=1500)
    chopper_max_operating_voltage: float = parameter(500.0, "V DC", "Maximum scheduled normal chopper target", "estimated", minimum=10, maximum=1500)
    chopper_band: float = parameter(40.0, "V", "Voltage rise above the scheduled target for a full-duty request", "estimated", minimum=1, maximum=500)
    chopper_response: float = parameter(0.02, "s", "Averaged chopper duty response time constant", "estimated", minimum=0.001, maximum=1)
    chopper_max_duty: float = parameter(1.0, "fraction", "Maximum allowed resistor duty", "estimated", maximum=1)
    chopper_max_current: float = parameter(2.0, "A DC", "Maximum averaged brake-chopper/resistor current", "estimated", minimum=0.01, maximum=1000)
    inverter_current_limit: float = parameter(3.0, "A RMS", "Phase current limit of the active exciter", "estimated", minimum=0.1, maximum=100)
    inverter_reactive_current_limit: float = parameter(3.0, "A RMS", "Reactive phase-current component limit of the active exciter", "estimated", minimum=0.1, maximum=100)
    inverter_output_resistance: float = parameter(5.0, "ohm/phase", "Virtual output impedance used by the averaged current controller; not heat", "estimated", minimum=0.01, maximum=100)
    inverter_conduction_resistance: float = parameter(0.25, "ohm/phase", "Physical equivalent inverter conduction resistance used only for heat", "estimated", minimum=0, maximum=100)
    inverter_idle_loss: float = parameter(3.0, "W", "Enabled converter overhead; legacy DC-fed mode also requires minimum DC voltage", "estimated", maximum=1000)
    inverter_min_dc_voltage: float = parameter(50.0, "V DC", "Below this voltage the averaged exciter is disabled", "estimated", minimum=1, maximum=1000)
    battery_voltage: float = parameter(24.0, "V DC", "Nominal auxiliary battery voltage", "estimated", minimum=1, maximum=100)
    battery_capacity_wh: float = parameter(480.0, "Wh", "Usable 24 V battery energy capacity", "estimated", minimum=1, maximum=100000)
    battery_initial_soc: float = parameter(100.0, "%", "Battery state of charge at Reset", "estimated", minimum=0, maximum=100)
    battery_discharge_current_limit: float = parameter(20.0, "A", "Maximum battery discharge current", "estimated", minimum=.01, maximum=1000)
    battery_charge_current_limit: float = parameter(10.0, "A", "Maximum battery charge current", "estimated", minimum=.01, maximum=1000)
    battery_internal_resistance: float = parameter(.05, "ohm", "Lumped battery internal resistance", "estimated", minimum=0, maximum=100)
    boost_target_voltage: float = parameter(520.0, "V DC", "Auxiliary regulated DC output; separate from brake DC link in battery-exciter mode", "estimated", minimum=10, maximum=1500)
    boost_input_power_limit: float = parameter(200.0, "W", "Maximum battery input power to the boost converter", "estimated", minimum=1, maximum=10000)
    boost_efficiency: float = parameter(0.9, "fraction", "Boost output/input efficiency", "estimated", minimum=0.1, maximum=1)
    boost_output_current_limit: float = parameter(1.0, "A DC", "Boost high-voltage output current limit, including initial charging", "estimated", minimum=0.01, maximum=100)
    boost_response: float = parameter(0.05, "s", "Boost output-current command response time", "estimated", minimum=0.001, maximum=10)
    boost_voltage_gain: float = parameter(0.02, "A/V", "Boost voltage-loop proportional gain", "estimated", minimum=0.0001, maximum=1)
    aux_capacitance: float = parameter(470.0, "µF", "Auxiliary high-voltage DC-link capacitor between boost and exciter", "estimated", minimum=10, maximum=100000)
    aux_initial_voltage: float = parameter(0.0, "V DC", "Auxiliary-link voltage at Reset", "estimated", maximum=1500)
    aux_ready_voltage: float = parameter(500.0, "V DC", "Minimum auxiliary-link voltage for field-building readiness", "estimated", minimum=1, maximum=1500)
    precharge_power_limit: float = parameter(100.0, "W", "Battery converter limit while precharging AC capacitors", "estimated", minimum=1, maximum=10000)
    precharge_efficiency: float = parameter(.85, "fraction", "Averaged capacitor-precharge converter efficiency", "estimated", minimum=.1, maximum=1)
    charger_power_limit: float = parameter(150.0, "W", "DC-link to battery charger input-power limit", "estimated", minimum=1, maximum=10000)
    charger_efficiency: float = parameter(.9, "fraction", "DC-link battery charger efficiency", "estimated", minimum=.1, maximum=1)
    charger_min_dc_voltage: float = parameter(50.0, "V", "DC-link voltage at which battery charging may begin", "estimated", minimum=1, maximum=1500)
    core_loss_resistance: float = parameter(4000.0, "ohm/phase", "Approximate core-loss branch referred to stator terminals", "estimated", minimum=100, maximum=1e12)
    gearbox_efficiency: float = parameter(1.0, "fraction", "Lowering gear efficiency; gravity-referred loss torque", "estimated", minimum=0.1, maximum=1)
    drivetrain_loss_torque: float = parameter(0.0, "N m", "Bearing/seal Coulomb loss torque at motor shaft", "estimated", maximum=100)
    external_supply_voltage: float = parameter(400.0, "V LL RMS", "Legacy comparison only; unused by the finite battery-exciter model", "known", minimum=10, maximum=1000)
    exciter_active_limit: float = parameter(200.0, "W", "Maximum positive exciter AC active output", "estimated", minimum=1, maximum=10000)
    exciter_run_active_limit: float = parameter(35.0, "W", "Maximum positive exciter AC power after brake release", "estimated", minimum=0, maximum=10000)
    exciter_absorption_limit: float = parameter(0.0, "W", "Deprecated compatibility input; reviewed exciter never absorbs AC real power", "estimated", maximum=100)
    exciter_flux_target: float = parameter(0.95, "Wb turn", "Peak magnetizing flux-linkage reference", "estimated", minimum=0.01, maximum=5)
    maximum_magnetic_flux: float = parameter(1.30, "Wb turn", "Maximum allowed estimated magnetizing flux before V/f derating", "estimated", minimum=0.01, maximum=10)
    motor_current_limit_rms: float = parameter(6.0, "A RMS", "Maximum intended machine phase-current magnitude for scalar V/f control", "estimated", minimum=0.1, maximum=1000)
    overcurrent_dwell: float = parameter(0.1, "s", "Time above the machine-current limit before a protection fault", "estimated", minimum=0.001, maximum=10)
    auxiliary_max_voltage: float = parameter(650.0, "V DC", "Auxiliary-link overvoltage protection limit", "estimated", minimum=10, maximum=2000)
    main_dc_max_voltage: float = parameter(650.0, "V DC", "Main DC-link overvoltage protection limit", "estimated", minimum=10, maximum=2000)
    minimum_control_frequency: float = parameter(5.0, "Hz", "Minimum intended controlled exciter frequency before mechanical braking", "estimated", minimum=0.1, maximum=100)
    frequency_accel_rate: float = parameter(15.0, "Hz/s", "Maximum scalar V/f frequency-command increase", "estimated", minimum=0.01, maximum=1000)
    frequency_decel_rate: float = parameter(3.0, "Hz/s", "Maximum scalar V/f frequency-command decrease", "estimated", minimum=0.01, maximum=1000)
    vf_limit_response: float = parameter(0.01, "s", "Current/flux derating response time", "estimated", minimum=0.001, maximum=10)
    vf_flux_kp: float = parameter(60.0, "V/Wb turn", "Scalar V/f flux-loop proportional gain", "estimated", minimum=0, maximum=10000)
    vf_flux_ki: float = parameter(200.0, "V/(Wb turn s)", "Scalar V/f flux-loop integral gain", "estimated", minimum=0, maximum=100000)
    vf_flux_correction_limit: float = parameter(150.0, "V LL RMS", "Maximum magnitude of normal scalar flux-loop voltage correction", "estimated", minimum=0, maximum=1500)
    sequence_normal_frequency: float = parameter(20.0, "Hz", "Canonical lowering frequency target", "estimated", minimum=0.1, maximum=100)
    sequence_slowdown_1_frequency: float = parameter(15.0, "Hz", "First canonical slowdown target", "estimated", minimum=0.1, maximum=100)
    sequence_slowdown_2_frequency: float = parameter(10.0, "Hz", "Second canonical slowdown target", "estimated", minimum=0.1, maximum=100)
    sequence_slowdown_3_frequency: float = parameter(7.5, "Hz", "Third canonical slowdown target", "estimated", minimum=0.1, maximum=100)
    sequence_slowdown_4_frequency: float = parameter(5.0, "Hz", "Final canonical controlled frequency", "estimated", minimum=0.1, maximum=100)
    sequence_ready_time: float = parameter(0.05, "s", "Electrical-ready dwell before brake release", "estimated", minimum=0, maximum=10)
    sequence_normal_hold: float = parameter(0.6, "s", "Canonical hold after reaching normal frequency", "estimated", minimum=0, maximum=60)
    sequence_slowdown_1_hold: float = parameter(0.5, "s", "Canonical hold after reaching first slowdown target", "estimated", minimum=0, maximum=60)
    sequence_slowdown_2_hold: float = parameter(0.4, "s", "Canonical hold at the second slowdown target", "estimated", minimum=0, maximum=60)
    sequence_slowdown_3_hold: float = parameter(0.4, "s", "Canonical hold at the third slowdown target", "estimated", minimum=0, maximum=60)
    sequence_slowdown_4_hold: float = parameter(0.4, "s", "Canonical hold at the final controlled frequency", "estimated", minimum=0, maximum=60)
    sequence_capacitor_hold: float = parameter(3.0, "s", "Canonical capacitor-only natural-lowering observation time", "estimated", minimum=0.01, maximum=120)
    sequence_stop_speed: float = parameter(0.005, "m/s", "Speed below which a physically applied brake qualifies STOPPED", "estimated", minimum=0, maximum=10)
    runaway_speed_limit: float = parameter(0.8, "m/s", "Simulation diagnostic lowering-speed limit", "estimated", minimum=0.01, maximum=100)
    runaway_min_export_power: float = parameter(20.0, "W", "Minimum useful export while diagnosing current-limited runaway", "estimated", minimum=0, maximum=100000)
    runaway_dwell: float = parameter(0.3, "s", "Duration of runaway evidence before FAULT", "estimated", minimum=0.001, maximum=10)
    startup_frequency: float = parameter(2.0, "Hz", "Low-frequency magnetization before brake release", "estimated", minimum=0.1, maximum=50)
    startup_flux_fraction: float = parameter(0.8, "fraction", "Required flux fraction before automatic brake release", "estimated", minimum=0.1, maximum=1)
    startup_dwell: float = parameter(0.2, "s", "Continuous magnetization qualification before release", "estimated", minimum=0.01, maximum=10)
    startup_ramp: float = parameter(0.3, "s", "Field-frequency ramp after brake release", "estimated", minimum=0.01, maximum=10)
    dc_precharge_resistance: float = parameter(150.0, "ohm", "Series resistance from bridge to main DC capacitor while K_PRECHARGE is closed", "estimated", minimum=0.1, maximum=100000)
    dc_precharge_close_fraction: float = parameter(0.90, "fraction", "Main-contactor close threshold relative to available rectified crest voltage", "estimated", minimum=0.1, maximum=0.999)
    dc_precharge_timeout: float = parameter(3.0, "s", "Maximum precharge duration before a latched startup fault", "estimated", minimum=0.01, maximum=60)

    def __post_init__(self):
        for item in fields(self):
            value = getattr(self, item.name)
            if not math.isfinite(value) or not item.metadata["minimum"] <= value <= item.metadata["maximum"]:
                raise ValueError(f"{item.name}: enter {item.metadata['minimum']} to {item.metadata['maximum']} {item.metadata['unit']}")
        if self.pole_pairs != int(self.pole_pairs):
            raise ValueError("pole_pairs must be an integer")
        if self.exciter_flux_target > self.maximum_magnetic_flux:
            raise ValueError("exciter_flux_target must not exceed maximum_magnetic_flux")
        if self.boost_target_voltage > self.auxiliary_max_voltage:
            raise ValueError("boost_target_voltage must not exceed auxiliary_max_voltage")
        if self.chopper_min_operating_voltage > self.chopper_max_operating_voltage:
            raise ValueError("chopper_min_operating_voltage must not exceed chopper_max_operating_voltage")
        if not (self.sequence_slowdown_4_frequency <= self.sequence_slowdown_3_frequency
                <= self.sequence_slowdown_2_frequency <= self.sequence_slowdown_1_frequency
                <= self.sequence_normal_frequency):
            raise ValueError("sequence frequencies must descend from normal through slowdown 1, 2, 3 and 4")
